import 'package:flutter_ar_app/core/resources/content/weapon/weapon.dart';
import 'package:flutter_ar_app/src/bloc/content_bloc/content_bloc.dart';
import 'package:flutter_ar_app/src/model/explore_card/explore_card.dart';

List<MuseumArtifactModel> weaponList = [
  MuseumArtifactModel(
    title: 'Pháo phòng không 100mm',
    subtitle: 'Pháo phòng không tự hành',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().artilery100mm,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/aa100mm.jpg',
  ),
  MuseumArtifactModel(
    title: 'Ra đa pháo COH-9A',
    subtitle: 'Ra đa pháo phòng không tự hành COH-9A',
    type: ContentCategory.weapon,
    weaponType: WeaponType.radar,
    description: WeaponContent().radarC0H9A,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/radacoh.jpg',
  ),
  MuseumArtifactModel(
    title: 'Pháo 90mm',
    subtitle: 'Pháo phòng không tự hành 90mm',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().aa90mm,
    manufacturer: 'Mỹ',
    image: 'lib/core/resources/images/content_images/weapon_images/aa90mm.jpg',
  ),
  MuseumArtifactModel(
    title: 'Pháo 85mm',
    subtitle: 'Pháo phòng không tự hành 85mm',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().aa85mm,
    manufacturer: 'Đức Quốc Xã',
    image: 'lib/core/resources/images/content_images/weapon_images/aa85mm.jpg',
  ),
  MuseumArtifactModel(
    title: 'Máy chỉ huy K59-03',
    subtitle: 'Máy chỉ huy phòng không chiến thuật K59-03',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().cmdPostK5903,
    manufacturer: 'Trung Quốc',
    image: 'lib/core/resources/images/content_images/weapon_images/cmdpost.jpg',
  ),
  MuseumArtifactModel(
    title: 'Xe pháo tự hành 3CY-23',
    subtitle: 'Xe pháo tự hành phòng không 3CY-23',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().artillery3CY23,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/aa3cy23.jpg',
  ),
  MuseumArtifactModel(
    title: 'Xe cẩu K-67',
    subtitle: 'Xe cẩu pháo tự hành K-67',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().truckK67,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/truck.jpg',
  ),
  MuseumArtifactModel(
    title: 'Tên lửa phòng không Petrora C-125M1',
    subtitle: 'Tên lửa phòng không chiến lược Petrora C-125M1',
    type: ContentCategory.weapon,
    weaponType: WeaponType.missile,
    description: WeaponContent().petroraC125M1missle,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/petrora.jpg',
  ),
  MuseumArtifactModel(
    title: 'Xe tính toán tên lửa Dvina',
    subtitle: 'Xe tính toán tên lửa phòng không chiến lược Dvina',
    type: ContentCategory.weapon,
    weaponType: WeaponType.missile,
    description: WeaponContent().dvinaMissletruck,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/dvina.jpg',
  ),
  MuseumArtifactModel(
    title: 'Súng 14.5mm',
    subtitle: 'Súng phòng không 14.5mm',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().gun14_5mm,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/aa145.jpg',
  ),
  MuseumArtifactModel(
    title: 'Xe pháo phòng không tự hành AM',
    subtitle: '',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().aaTruckAm,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/artiam.jpg',
  ),
  MuseumArtifactModel(
    title: 'Xe pháo tự hành 37mm',
    subtitle: '',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().artillery37mm,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/aa37mm.jpg',
  ),
  MuseumArtifactModel(
    title: 'Xe pháo tự hành 57mm',
    subtitle: '',
    type: ContentCategory.weapon,
    weaponType: WeaponType.artillery,
    description: WeaponContent().artillery57mm,
    manufacturer: 'Liên Xô',
    image: 'lib/core/resources/images/content_images/weapon_images/aa57mm.jpg',
  ),
  MuseumArtifactModel(
    title: 'Ra đa Petrora',
    subtitle: '',
    type: ContentCategory.weapon,
    weaponType: WeaponType.radar,
    description: WeaponContent().petroraRadar,
    manufacturer: 'Liên Xô',
    image:
        'lib/core/resources/images/content_images/weapon_images/radapetrora.jpg',
  ),
];
